### ISSUE TITLE
Running controller fails on windows in powershell

### ISSUE THREAD

**Issue by AncientSwordRage** [iatorm/grid-routing-battle#1]
Hi I tried to run the controller, but it's failed..not sure how to troubleshoot.

```
PS C:\Users\folder\grid-routing-battle> .\controller.py
Initializing bots.
Bots:
  Random Builder
  Checkpoint
  FaucetBot
  Connector
Running 100 rounds.
  Round 0
Traceback (most recent call last):
  File "C:\Users\folder\grid-routing-battle\controller.py", line 234, in <module>
    main()
  File "C:\Users\folder\grid-routing-battle\controller.py", line 222, in main
    slow_bots.update(run_round(bots))
  File "C:\Users\folder\grid-routing-battle\controller.py", line 83, in run_round
    bot.handle = sub.Popen(bot.command, bufsize=1, universal_newlines=True, cwd=directory, stdin=sub.PIPE, stdout=sub.PI
PE)
  File "C:\Python34\lib\subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1111, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by iatorm** [comment]
Do you have your Java executable in your PATH environment variable? That's all I can think of now. I know that the controller has trouble with Java submissions on Windows, and I haven't been able to fix it yet.

**Comment by iatorm** [comment]
I issued a patch. I haven't tested it on Windows, but it should at least offer a more meaningful error message.
